#!/usr/bin/env python3
"""
Install Mock Modules

This script sets up the mock modules directory in the Python path.
It also creates symlinks or copies of mock modules to the site-packages directory
if needed for deployment environments where direct imports fail.
"""

import os
import sys
import shutil
import logging
import importlib.util
import site

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('install_mock_modules')

# List of modules to be mocked
MOCK_MODULES = [
    'plyer',
    'polygon',
    'alpaca_trade_api',
]

def ensure_mock_dir():
    """Ensure the mock_modules directory exists"""
    mock_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'mock_modules')
    if not os.path.exists(mock_dir):
        logger.info(f"Creating mock_modules directory at {mock_dir}")
        os.makedirs(mock_dir, exist_ok=True)
    return mock_dir

def check_module_installed(module_name):
    """Check if a module is already installed"""
    try:
        spec = importlib.util.find_spec(module_name)
        return spec is not None
    except ImportError:
        return False

def install_mock_modules():
    """Install mock modules to site-packages"""
    mock_dir = ensure_mock_dir()
    site_packages = site.getsitepackages()[0]
    
    logger.info(f"Using site-packages directory: {site_packages}")
    
    for module_name in MOCK_MODULES:
        if check_module_installed(module_name):
            logger.info(f"Module {module_name} is already installed, skipping mock")
            continue
            
        mock_file = os.path.join(mock_dir, f"{module_name}.py")
        site_module_dir = os.path.join(site_packages, module_name)
        
        if not os.path.exists(mock_file):
            logger.warning(f"Mock file {mock_file} does not exist, creating empty stub")
            with open(mock_file, 'w') as f:
                f.write(f'"""\nEmpty stub for {module_name} module\n"""\n\n')
        
        if os.path.exists(site_module_dir):
            logger.info(f"Removing existing module at {site_module_dir}")
            if os.path.isdir(site_module_dir):
                shutil.rmtree(site_module_dir)
            else:
                os.remove(site_module_dir)
        
        # Create the module directory
        os.makedirs(site_module_dir, exist_ok=True)
        
        # Create an __init__.py file that imports from our mock
        init_file = os.path.join(site_module_dir, "__init__.py")
        with open(init_file, 'w') as f:
            f.write(f'''"""
Mock {module_name} module

This is automatically generated by install_mock_modules.py
"""

import sys
import os
import importlib
import logging

# Get the root path where mock modules are stored
ROOT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOCK_PATH = os.path.join(ROOT_PATH, "mock_modules")

# Add mock_modules to sys.path if not already there
if MOCK_PATH not in sys.path:
    sys.path.insert(0, MOCK_PATH)

try:
    # Try to import the mock module
    mock_module = importlib.import_module("{module_name}")
    
    # Copy all attributes from the mock module
    for attr in dir(mock_module):
        if not attr.startswith('_'):
            globals()[attr] = getattr(mock_module, attr)
            
except Exception as e:
    logging.error(f"Failed to import mock {module_name}: {{e}}")
''')
        
        logger.info(f"Created mock module for {module_name} at {site_module_dir}")

if __name__ == "__main__":
    logger.info("Starting mock modules installation")
    install_mock_modules()
    logger.info("Mock modules installation completed")
    
    # Add the mock_modules directory to the Python path
    mock_dir = ensure_mock_dir()
    if mock_dir not in sys.path:
        sys.path.insert(0, mock_dir)
        logger.info(f"Added {mock_dir} to Python path") 