<<<<<<< Updated upstream
<<<<<<< Updated upstream
// Auto-generated file to indicate real data source
const dataSourceMarker = {
  source: "api",
  isRealData: true,
  timestamp: 1745104143.1169257
};

export default dataSourceMarker;
=======
// Auto-generated by ensure_real_data.py on 2025-04-26T15:33:48.888636
const DATA_SOURCE = 'alpaca';
const IS_REAL_DATA = true;

export const getDataSourceInfo = () => {
  return {
    source: DATA_SOURCE,
    isRealData: IS_REAL_DATA,
    lastUpdated: '2025-04-26T15:33:48.888666'
  };
};

=======
// Auto-generated by ensure_real_data.py on 2025-04-26T15:33:48.888636
const DATA_SOURCE = 'alpaca';
const IS_REAL_DATA = true;

export const getDataSourceInfo = () => {
  return {
    source: DATA_SOURCE,
    isRealData: IS_REAL_DATA,
    lastUpdated: '2025-04-26T15:33:48.888666'
  };
};

>>>>>>> Stashed changes
export default {
  source: DATA_SOURCE,
  isRealData: IS_REAL_DATA
};
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
